# Generated by Django 3.2.18 on 2023-06-08 14:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('인원모집', '인원모집'), ('자유게시판', '자유게시판'), ('공지사항', '공지사항'), ('뉴스', '뉴스')], default='공지사항', max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('contents', models.TextField(null=True)),
                ('topic', models.CharField(blank=True, choices=[('스터디', '스터디'), ('프로젝트', '프로젝트'), ('공모전', '공모전')], max_length=30, null=True)),
                ('total_personnel', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('now_personnel', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('place', models.CharField(choices=[('온라인', '온라인'), ('오프라인', '오프라인')], default='오프라인', max_length=5)),
                ('project_term', models.DateField()),
                ('language', models.JSONField(default=dict)),
                ('skill', models.JSONField(default=dict)),
                ('is_recruiting', models.BooleanField(default=True)),
                ('expired_date', models.DateField()),
                ('explain', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='post_like', to=settings.AUTH_USER_MODEL)),
                ('scraps', models.ManyToManyField(blank=True, related_name='post_scrap', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_secret', models.BooleanField(default=False)),
                ('likes', models.ManyToManyField(blank=True, related_name='comment_like', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
